# Generated by Django 4.1.6 on 2023-03-28 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('size', models.CharField(default='', max_length=200)),
                ('mrp', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default='')),
                ('desc', models.CharField(default='', max_length=5000)),
                ('desc2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('image', models.FileField(default='', upload_to='images/')),
                ('availabilty', models.IntegerField(default=1)),
                ('directions', models.CharField(default='', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('product', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=250)),
                ('user_review', models.CharField(max_length=3000, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(max_length=5000)),
                ('rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='prod_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('prod', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
