# Generated by Django 4.1.6 on 2023-03-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('sizes', models.CharField(default='', max_length=200)),
                ('mrps', models.CharField(default='', max_length=200)),
                ('sale_prices', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=5000)),
                ('desc2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('image', models.FileField(default='', upload_to='images/')),
                ('availabilty', models.IntegerField(default=1)),
                ('directions', models.CharField(default='', max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='prod_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
