# Generated by Django 4.1.6 on 2023-03-28 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='used_by',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
