# Generated by Django 4.1.6 on 2023-03-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mrps',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_prices',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sizes',
            new_name='size',
        ),
    ]
