# Generated by Django 4.1.6 on 2023-03-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sales_rename_mrps_product_mrp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prod_images',
            old_name='post',
            new_name='prod',
        ),
    ]
