# Generated by Django 4.1.6 on 2023-03-28 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_couponcode_discount_couponcode_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 21, 22, 47, 15797)),
        ),
    ]
