# Generated by Django 4.1.6 on 2023-03-28 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_couponcode_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='validity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
