# Generated by Django 4.1.6 on 2023-03-29 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_couponcode_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=2000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=300)),
                ('Address', models.CharField(default='', max_length=1000)),
                ('postal_code', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('coupon_used', models.CharField(default='', max_length=50)),
                ('instructions', models.CharField(default='', max_length=2000)),
                ('city', models.CharField(default='', max_length=200)),
                ('payment_ref', models.CharField(default='', max_length=25)),
                ('delivered', models.IntegerField(default=0)),
                ('dispatched', models.IntegerField(default=0)),
                ('payment_conf', models.IntegerField(default=0)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('link', models.CharField(default='nil', max_length=5000)),
                ('declined', models.IntegerField(default=0)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
