# Generated by Django 4.1.6 on 2023-03-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_review_id_review_user_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
