# Generated by Django 4.1.6 on 2023-04-01 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_orders_order_id_alter_orders_payment_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='number_of_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
