# Generated by Django 4.1.6 on 2023-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_orders_order_id_alter_orders_payment_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=5000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
