# Generated by Django 4.1.6 on 2023-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_orders_declined_alter_orders_delivered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[['bodyoils', 'bodyoils'], ['bodywash', 'body wash']], default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('size', models.CharField(default='', max_length=200)),
                ('mrp', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default='')),
                ('desc', models.CharField(default='', max_length=5000)),
                ('desc2', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('availabilty', models.IntegerField(default=1)),
                ('directions', models.CharField(default='', max_length=4000)),
            ],
        ),
    ]
