# Generated by Django 4.1.6 on 2023-04-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product1',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[['bodyoils', 'body oils'], ['bodywash', 'body wash']], default='', max_length=50),
        ),
    ]
