# Generated by Django 4.1.6 on 2023-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_product1_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=5000)),
                ('email', models.CharField(default='', max_length=5000)),
                ('subject', models.CharField(default='', max_length=5000)),
                ('msg', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
